name: CI devops 2024
on:
  push:
    branches: 
      - main # Exécute le pipeline sur la branche principale
      - develop # Exécute aussi sur la branche de développement
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Étape 1 : Récupère le code depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape 2 : Configure JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      # Étape 3 : Compile et teste l'application avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml
